# Generated by Django 6.0 on 2026-01-08 12:20

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="QnALog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Git", "Git"),
                            ("Linux", "Linux"),
                            ("DB", "DB"),
                            ("Python", "Python"),
                            ("Flask", "Flask"),
                            ("Django", "Django"),
                            ("FastAPI", "FastAPI"),
                            ("General", "General"),
                        ],
                        default="General",
                        max_length=50,
                        verbose_name="카테고리",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("question_text", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="qna_images/"),
                ),
                ("ai_answer", models.TextField()),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="검증 완료"),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(default=1, verbose_name="질문 빈도"),
                ),
                (
                    "notion_page_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="노션 페이지 링크",
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True, default=list, null=True, verbose_name="세부 키워드"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "parent_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_questions",
                        to="archiver.qnalog",
                        verbose_name="상위 질문",
                    ),
                ),
            ],
            options={
                "verbose_name": "Q&A Log",
                "verbose_name_plural": "Q&A 로그 목록",
                "ordering": ["-created_at"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["question_text"],
                        name="qna_question_tgrm_idx",
                        opclasses=["gin_trgm_ops"],
                    )
                ],
            },
        ),
    ]
