# Generated by Django 6.0 on 2026-01-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiver", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qnalog",
            name="hit_count",
            field=models.PositiveIntegerField(default=0, verbose_name="질문 빈도"),
        ),
        migrations.AlterField(
            model_name="qnalog",
            name="keywords",
            field=models.TextField(blank=True, null=True, verbose_name="세부 키워드"),
        ),
    ]
