# Generated by Django 6.0 on 2026-02-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiver", "0002_alter_qnalog_hit_count_alter_qnalog_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qnalog",
            name="category",
            field=models.CharField(
                default="General", max_length=50, verbose_name="카테고리"
            ),
        ),
    ]
